# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: 0
  minorVersion: 2
  patchVersion: $[counter(variables['minorVersion'], 0)]
  version: $(majorVersion).$(minorVersion).$(patchVersion)

name: $(majorVersion).$(minorVersion).$(patchVersion)

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.0.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/ietws.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'