# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: 0
  minorVersion: 2
  patchVersion: $[counter(variables['minorVersion'], 0)]
  version: $(majorVersion).$(minorVersion).$(patchVersion)

name: $(version)

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(version)'

